[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
memecoin_prediction_market = "CBEPKK5C5CYDbCDhsk1TaFLUXVNnw7QnXTc2ueqTgXvy"

[programs.devnet]
memecoin_prediction_market = "CBEPKK5C5CYDbCDhsk1TaFLUXVNnw7QnXTc2ueqTgXvy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
